### ISSUE TITLE
[Low priority] Object can appear twice

### ISSUE THREAD

**Issue by Bertware** [julianrojas87/linked-connections-server#3]
On graph.irail.be, the following excerpt can be found in the result for https://graph.irail.be/sncb/connections?departureTime=2018-02-15T13:40:00.000Z

```
  {
    "@id": "http:\/\/irail.be\/connections\/8821717\/20180215\/IC4314",
    "@type": "Connection",
    "departureStop": "http:\/\/irail.be\/stations\/NMBS\/008821717",
    "arrivalStop": "http:\/\/irail.be\/stations\/NMBS\/008832458",
    "departureTime": "2018-02-15T13:43:00.000Z",
    "arrivalTime": "2018-02-15T13:49:00.000Z",
    "direction": "Hamont",
    "gtfs:trip": "http:\/\/irail.be\/vehicle\/IC4314\/20180215",
    "gtfs:route": "http:\/\/irail.be\/vehicle\/IC4314",
    "gtfs:pickupType": "gtfs:Regular",
    "gtfs:dropOffType": "gtfs:Regular"
  },
  {
    "@id": "http:\/\/irail.be\/connections\/8821717\/20180215\/IC4314",
    "@type": "Connection",
    "departureStop": "http:\/\/irail.be\/stations\/NMBS\/008821717",
    "arrivalStop": "http:\/\/irail.be\/stations\/NMBS\/008832458",
    "departureTime": "2018-02-15T13:43:00.000Z",
    "arrivalTime": "2018-02-15T13:49:00.000Z",
    "direction": "Hasselt",
    "gtfs:trip": "http:\/\/irail.be\/vehicle\/IC4314\/20180215",
    "gtfs:route": "http:\/\/irail.be\/vehicle\/IC4314",
    "gtfs:pickupType": "gtfs:Regular",
    "gtfs:dropOffType": "gtfs:Regular"
  }
```

Only one of those should be shown as they are identical

**Comment by julianrojas87** [comment]
In close inspection they are not identical. The direction is different, one has `"direction": "Hamont"` and the other `"direction": "Hasselt"` and checking the GTFS feed, there are two different trips specified that are the source for these connections:

`route_id,service_id,trip_id,trip_headsign,trip_short_name,direction_id,block_id,shape_id,trip_type`
`228,000383,88____:007::8821006:8832664:17:1538:20181208,Hamont,4314,,6806,,1`
`145,000383,88____:007::8821006:8832409:13:1502:20181208,Hasselt,4314,,6807,,1` 

The problem seems to lie on how the identifiers are built for these connections. Maybe the parameter `direction_id` could be used to unique identify the connections.

**Comment by julianrojas87** [comment]
Understood.
